/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Sarita Chinchilla
 */
public class Parcial_1 extends javax.swing.JFrame {

    /**
     * Creates new form Parcial_1
     */
    public Parcial_1() {
        initComponents();
         String[] productos={"Cemento 'Tolteca'","Cal","Tubo PC","Hierro"};
        for(int i=0;i<productos.length;i++)
        {
            listado.addItem(productos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Cantidad = new javax.swing.JTextField();
        nomfact = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        listado = new javax.swing.JComboBox<>();
        Peso = new javax.swing.JTextField();
        articulo = new javax.swing.JTextField();
        informe = new javax.swing.JButton();
        precio = new javax.swing.JTextField();
        nominf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablitas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabel3.setText("Cantidad");

        jButton3.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jButton3.setText("Facturar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nomfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfactActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jButton1.setLabel("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabel4.setText("Peso");

        listado.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoActionPerformed(evt);
            }
        });

        Peso.setEditable(false);

        articulo.setEditable(false);
        articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloActionPerformed(evt);
            }
        });

        informe.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        informe.setText("Generar informe");
        informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeActionPerformed(evt);
            }
        });

        precio.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabel1.setText("Articulo");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabel2.setText("Precio");

        tablitas.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        tablitas.setForeground(new java.awt.Color(0, 0, 255));
        tablitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Precio", "Peso", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 479, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(nomfact, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(172, 172, 172))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(130, 130, 130))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(informe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nominf)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(283, 283, 283)
                                    .addComponent(jLabel1)
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabel2)
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabel4)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(123, 123, 123)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jButton2)
                .addGap(54, 54, 54)
                .addComponent(nomfact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(nominf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(informe))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Se crea el documento
        Document document = new Document() ;

        try {

            String path = new File("C://tmp// ").getCanonicalPath();
            String FILE_NAME = path + nomfact.getText()+".pdf";

            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(new File(FILE_NAME)));
            document.open();
            Paragraph parrafo = new Paragraph();
            int t=0;
            int p;

            for (int i = 0; i < tablitas.getRowCount(); i++) {
                /* System.out.println("Registro número: "+i);
                System.out.println("ID: "+tablitas.getValueAt(i, 0));
                System.out.println("NOMBRE: "+tablitas.getValueAt(i, 1));
                System.out.println("TELÉFONO: "+tablitas.getValueAt(i, 2));*/

                parrafo.add("Articulo "+tablitas.getValueAt(i, 0)+"\n");
                parrafo.add("Precio  Q"+tablitas.getValueAt(i, 1)+" \n");
                parrafo.add("Peso Kgs"+tablitas.getValueAt(i, 2)+"\n");
                parrafo.add("Cantidad"+tablitas.getValueAt(i, 3)+"\n");
                parrafo.add("Total Q"+tablitas.getValueAt(i, 4)+"\n");
            }
            if(nomfact.equals(" "))
            {
                JOptionPane.showMessageDialog(rootPane,"no hay un nombre para guardar la factura");
            }

            document.add(parrafo);
            document.close();
            JOptionPane.showMessageDialog(rootPane,"guardado");

        } catch (FileNotFoundException | DocumentException e)
        {
            JOptionPane.showMessageDialog(rootPane, "No hay nada para guardar");

        } catch (IOException ex) {
            Logger.getLogger(Parcial_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nomfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomfactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int presio=Integer.parseInt(precio.getText());
        int pesor=Integer.parseInt(Peso.getText());
        String art=articulo.getText();
        int cantidades=Integer.parseInt(Cantidad.getText());
        int totales=presio*cantidades;
        Object[] fr={art,presio,pesor,cantidades,totales};
        DefaultTableModel table =(DefaultTableModel) tablitas.getModel();
        table.addRow(fr);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        articulo.setText(listado.getSelectedItem().toString());
        if(articulo.getText().equals("Cemento 'Tolteca'"))
        {
            precio.setText("60");
            Peso.setText("50");
        }
        if(articulo.getText().equals("Cal"))
        {
            precio.setText("40");
            Peso.setText("20");
        }
        if(articulo.getText().equals("Tubo PC"))
        {
            precio.setText("55");
            Peso.setText("10");
        }
        if(articulo.getText().equals("Hierro"))
        {
            precio.setText("350");
            Peso.setText("50");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoActionPerformed

    }//GEN-LAST:event_listadoActionPerformed

    private void articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articuloActionPerformed
public int total;
public double coe;
public float as;
    private void informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeActionPerformed
        
        Document document = new Document() ;
        try {
          
        	String path = new File("C://tmp// ").getCanonicalPath();
        	String FILE_NAME = path+" prorrateo" + nominf.getText()+".pdf";
        	
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(new File(FILE_NAME)));
            document.open(); 
            Paragraph parrafos = new Paragraph();
            int sa=0;
            for (int i = 0; i < tablitas.getRowCount(); i++)
            {
                var f=Integer.parseInt(tablitas.getValueAt(i, 4).toString());
               sa+=f;
            }
            tablitas.getRowCount();
            tablitas.getColumnCount();
             parrafos.add("el total es de: Q"+sa);
             
             //suma de gastos 
             int gastos=8700;
        
             parrafos.add("\nEl total de costos es de: Q"+gastos);
             //coeficiente de gastos
              coe=(double) gastos/sa;
             parrafos.add("\nel coheficiente de gastos es de: "+coe);
             //coheficiente de gastos de cada articulo
             int o;
              for (int i = 0; i < tablitas.getRowCount(); i++)
            {
               o=Integer.parseInt(tablitas.getValueAt(i,1).toString());
               as=(float)(coe*o);
               parrafos.add("\nprecio "+tablitas.getValueAt(i,1));
               parrafos.add("\n coeficiente: "+as);
               
            }
              //peso total del pedido.
              int pesado,cantidad,totaliado=0;
               for (int i = 0; i < tablitas.getRowCount(); i++)
            {
               pesado=Integer.parseInt(tablitas.getValueAt(i, 2).toString());
               cantidad=Integer.parseInt(tablitas.getValueAt(i, 3).toString());
               totaliado+=pesado*cantidad;
                parrafos.add("\npeso total"+totaliado);
            }
            
             document.add(parrafos);
              document.close();
            JOptionPane.showMessageDialog(rootPane,"guardado");
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_informeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parcial_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parcial_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parcial_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parcial_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parcial_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Peso;
    private javax.swing.JTextField articulo;
    private javax.swing.JButton informe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listado;
    private javax.swing.JTextField nomfact;
    private javax.swing.JTextField nominf;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tablitas;
    // End of variables declaration//GEN-END:variables
}
